### ISSUE TITLE
Is this project open source hardware and/or open source software?

### ISSUE THREAD

**Issue by abetusk** [humancomputerintegration/LipIO#1]
From your [README.md](https://github.com/humancomputerintegration/LipIO/blob/master/README.md) file:

> LipIO is an open-source device ...

As of this writing, this project is, as far as I can tell, "closed source" (at least here in the US) since there is no indication about what license is that the project falls under. I don't see a LICENSE file for the project nor do I see license file headers in the non third party source files. If I've missed these, my apologies.

"Open Source" has a generally accepted meaning of being able to use the digital artifacts for commercial purposes. The [OSI](https://opensource.org/osd/) and Wikipedia's entry on [open-source licensing](https://en.wikipedia.org/wiki/Open-source_license) both articulate that commercial re-use is a (generally accepted) requirement of an "open source" license.

The [Open Source Hardware Association](https://www.oshwa.org/definition/) articulates requirements of design files to meet their "open source" standards:

> Open source hardware is hardware whose design is made publicly available so that anyone can study, modify, distribute, make, and sell the design or hardware based on that design.

Without licensing information about the various digital artifacts (BOM, schematic, Gerbers, source code, etc.), the default is for them to fall under copyright protection and are not allowed to be copied, modified or distributed without explicit consent.

Was the intent to make this project libre/free/open source software/hardware?

If so, could you indicate the license, either by providing a LICENSE file with the appropriate license or by putting a license preamble in each of the source files (preferably both).

If not, it might be good to clarify what the restrictions are to avoid confusion. For example, indicating that the source is available, rather than it being open source.

**Comment by ajingu** [comment]
Hi, abetusk

I am Arata Jingu, the corresponding author of this work. Thanks for pointing it out.
This repository is supposed to be open-source software codes.
I'm attending a research conference this week, so will add a LICENSE file next week.

Thanks,
Arata
